spring.application.name=steamgram-api
server.port=8080

spring.datasource.url=jdbc:h2:mem:steamgramdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true


# JWT
app.security.jwt.secret=${JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_SECRET_CHANGE_ME}

# Rutas
app.security.routes.public[0]=/api/auth/**
app.security.routes.public[1]=/api/user/check/**
app.security.routes.public[2]=/swagger-ui/**
app.security.routes.public[3]=/v3/api-docs/**
app.security.routes.protected[0]=/api/**

# Usuarios y roles
app.security.users[0].username=collab
app.security.users[0].password=collab123
app.security.users[0].roles[0]=COLLABORATOR

# Permisos esperados por rol
app.security.permissions.collaborator.canCreate=true
app.security.permissions.collaborator.canDelete=false

app.security.permissions.admin.canCreate=true
app.security.permissions.admin.canEditAny=true
app.security.permissions.admin.canDelete=true

springdoc.swagger-ui.path=/swagger-ui.html