/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/games` | `/games`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/users` | `/users`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/users/[username]` | `/users/[username]`, params: Router.UnknownInputParams & { username: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/community` | `/community`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/games` | `/games`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/users` | `/users`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/users/[username]` | `/users/[username]`, params: Router.UnknownOutputParams & { username: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/community${`?${string}` | `#${string}` | ''}` | `/community${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/games${`?${string}` | `#${string}` | ''}` | `/games${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/users${`?${string}` | `#${string}` | ''}` | `/users${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/games` | `/games`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/users` | `/users`; params?: Router.UnknownInputParams; } | `${'/(app)'}/users/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/users/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/users/[username]` | `/users/[username]`, params: Router.UnknownInputParams & { username: string | number; } };
    }
  }
}
